export enum ActionType {
  // TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE',
  UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE',
  GET_VIDEO_DATA = 'GET_VIDEO_DATA',
  GET_SPOTIFY_DATA = 'GET_SPOTIFY_DATA',
  GET_APPLE_MUSIC_DATA = 'GET_APPLE_MUSIC_DATA',
  GET_AMAZON_MUSIC_DATA = 'GET_AMAZON_MUSIC_DATA',
  GET_SOUNDCLOUD_DATA = 'GET_SOUNDCLOUD_DATA',
}
